src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'), name='recipes'),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register, name='register')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, add_recipe, update_recipe, delete_recipe

app_name = 'recipes'

urlpatterns = [
  path('', home),
  path('list/', RecipeListView.as_view(), name='list'),
  path('list/<pk>', RecipeDetailView.as_view(), name='details'),
  path('add_recipe/', add_recipe, name='add_recipe'),
  path('update_recipe/<pk>', update_recipe, name='update_recipe'),
  path('delete_recipe/<pk>', delete_recipe, name='delete_recipe'),
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipe(models.Model):
  # model definition
  name = models.CharField(max_length=100)
  ingredients = models.CharField(max_length=400, help_text="Separate ingredients with a comma")
  cooking_time = models.PositiveSmallIntegerField(help_text='in minutes')
  directions = models.TextField(default='no directions')
  difficulty = models.CharField(max_length=20, blank=True, help_text='Leave blank, this will be auto-calculated')
  image = models.ImageField(upload_to='recipes', default='no_image.svg')

  # calculates difficulty of the recipe
  def calculate_difficulty(self):
    ingredients = self.ingredients.split(', ')
    if self.cooking_time < 15 and len(ingredients) < 5:
      difficulty = 'Easy'
    if self.cooking_time < 15 and len(ingredients) >= 5:
      difficulty = 'Medium'
    if self.cooking_time >= 15 and len(ingredients) < 5:
      difficulty = 'Intermediate'
    if self.cooking_time >= 15 and len(ingredients) >= 5:
      difficulty = 'Hard'

    return difficulty
  
  # string representation of the recipe
  def __str__(self):
    return str(self.name)
  
  # gets url for each recipe list item based on primary key (id)
  def get_absolute_url(self):
    return reverse('recipes:details', kwargs={'pk': self.pk})
  
  def save(self, *args, **kwargs):
    self.difficulty = self.calculate_difficulty()
    super().save(*args, **kwargs)

src/recipes/forms.py
from django import forms
from django.forms import TextInput, NumberInput, Textarea
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Recipe

# define chart selection choices
chart_choices = (
  ('bar chart', 'Bar chart of most used ingredients'),
  ('pie chart', 'Pie chart of recipe difficulty distribution'),
  ('line chart', 'Line chart of cooking time of each recipe')
)

# define the search form implemented in recipes_list.html
class RecipeSearchForm(forms.Form):
  recipe_name = forms.CharField(required=False, max_length=100)
  ingredient = forms.CharField(required=False, max_length=100)
  min_cooking_time = forms.IntegerField(required=False, min_value=0, label='Minimum cooking time:')
  max_cooking_time = forms.IntegerField(required=False, min_value=0, label='Maximum cooking time:')
  chart_type = forms.ChoiceField(choices=chart_choices, required=False, label='Chart selection')

# define a form for adding and updating recipes
class RecipeForm(forms.ModelForm):
  class Meta:
    model = Recipe
    fields = ['name', 'ingredients', 'cooking_time', 'directions', 'difficulty', 'image']
    # adding customization to the form field widgets
    widgets = {
      'name': TextInput(attrs={'class': 'form-control'}),
      'ingredients': TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ingredient 1, ingredient 2, ingredient 3'
        }),
      'cooking_time': NumberInput(attrs={'class': 'form-control'}),
      'directions': Textarea(attrs={
        'class': 'form-control',
        'style': 'height: 10vh;'
      })
    }

# define a user registration form
class UserRegistrationForm(UserCreationForm):
  email = forms.EmailField(required=True)

  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']

src/recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib import messages
import pandas as pd
from .models import Recipe
from .forms import RecipeSearchForm, RecipeForm
from .utils import get_bar_chart, get_pie_chart, get_line_chart

# Create your views here.
# defines the home page
def home(request):
  return render(request, 'recipes/recipes_home.html')

# defines the recipe list view
class RecipeListView(LoginRequiredMixin, ListView):
  model = Recipe
  template_name = 'recipes/recipes_list.html'
  search_form = RecipeSearchForm()

  # customizes get_queryset method to retrieve recipe list based on search parameters
  def get_queryset(self):
    queryset = super().get_queryset()

    # extract parameters from the request object
    recipe_name = self.request.GET.get('recipe_name')
    ingredient = self.request.GET.get('ingredient')
    min_cooking_time = self.request.GET.get('min_cooking_time')
    max_cooking_time = self.request.GET.get('max_cooking_time')

    # filter the queryset based on provided parameters
    if recipe_name:
      queryset = queryset.filter(name__icontains=recipe_name)
    if ingredient:
      queryset = queryset.filter(ingredients__icontains=ingredient)
    #filter for cooking time input options
    if min_cooking_time and max_cooking_time:
      queryset = queryset.filter(cooking_time__gte=min_cooking_time, cooking_time__lte=max_cooking_time)
    elif min_cooking_time:
      queryset = queryset.filter(cooking_time__gte=min_cooking_time)
    elif max_cooking_time:
      queryset = queryset.filter(cooking_time__lte=max_cooking_time)

    # return the filtered queryset
    return queryset
  
  # customizes the get_context_data method and data added to context is passed to template
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)  #gather context data from parent class
    queryset = self.get_queryset()
    recipe_list = list(queryset.values('id', 'name', 'ingredients', 'cooking_time', 'directions', 'difficulty', 'image'))

    # pass search, add recipe, and chart select forms into context
    context['search_form'] = RecipeSearchForm(self.request.GET)
    context['add_form'] = RecipeForm()

    # get the user selected chart and pass it to the template
    chart_selection = self.request.GET.get('chart_type')
    if chart_selection == 'bar chart': 
      context['bar_chart'] = get_bar_chart(recipe_list)
    elif chart_selection == 'pie chart':
      queryset = self.get_queryset()
      context['pie_chart'] = get_pie_chart(recipe_list)
    elif chart_selection == 'line chart':
      queryset = self.get_queryset()
      context['line_chart'] = get_line_chart(recipe_list)
    
    return context

# defines the recipe details view
# appears when user clicks on the recipe name from list view
class RecipeDetailView(LoginRequiredMixin, DetailView):
  model = Recipe
  template_name = 'recipes/recipe_details.html'

  # pass update form to the view through context
  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['update_form'] = RecipeForm()
    return context

# view to add recipes to the database
@login_required
def add_recipe(request):
  if request.method == 'POST':
    add_form = RecipeForm(request.POST, request.FILES)
    if add_form.is_valid():
      add_form.save()
      messages.success(request, 'Recipe added successfully!')
      return redirect('recipes:list')
    else:
      messages.error(request, 'Unable to add recipe, please try again.')
  else:
    add_form = RecipeForm()

# view to update an existing recipe
@login_required
def update_recipe(request, pk):
  recipe = get_object_or_404(Recipe, pk=pk)
  if request.method == 'POST':
    update_form = RecipeForm(request.POST, request.FILES, instance=recipe)
    if update_form.is_valid():
      update_form.save()
      messages.success(request, 'Recipe updated successfully!')
      return redirect('recipes:details', pk=recipe.pk)
    else:
      messages.error(request, 'Unable to update recipe, please try again.')
  else:
    update_form = RecipeForm(instance=recipe)

# view to delete a recipe
@login_required
def delete_recipe(request, pk):
  recipe = get_object_or_404(Recipe, pk=pk)
  if request.method == 'POST':
    recipe.delete()
    messages.success(request, 'Recipe deleted successfully!')
    return redirect('recipes:list')

src/recipes/templates/recipes/recipe_details.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,200;0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <!-- CSS for development, prevents cache loading file -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}?{% now 'U' %}"> -->
    <title>Recipe App</title>
  </head>
  <body class="recipe-details-page">
    <header class="recipes-list-header">
      <nav class="nav-bar">
        <p class="nav-title">Recipe App</p>
        <a href ="{% url 'logout' %}" class="logout-link">Logout</a>
      </nav>
    </header>
    {% if messages %}
      {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
      {% endfor %}
    {% endif %}
    <!-- Display recipe info -->
    <div style="text-align: center;">
      <h2 class="details-title">Recipe for {{object.name}}</h2>
      <img src="{{object.image.url}}" class="details-image" alt="Image of {{object.name}}">
    </div>
    <p> <b>Ingredients: </b> {{object.ingredients}}</p>
    <p> <b>Cooking Time: </b> {{object.cooking_time}} minutes</p>
    <p> <b>Difficulty: </b> {{object.difficulty}}</p>
    <p> <b>Directions: </b> {{object.directions}} </p>
    <!-- Update recipe modal -->
    <div class="modal fade" id="update-recipe-modal" tabindex="-1" aria-labelledby="update-recipe-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="update-recipe-modal-label">Update Recipe</h3>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="POST" id="update-recipe-form" action="{% url 'recipes:update_recipe' object.id %}" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="modal-form-field">
                {{update_form.name.label_tag}}
                {{update_form.name}}
              </div>
              <div class="modal-form-field">
                {{update_form.ingredients.label_tag}}
                {{update_form.ingredients}}
                <small>Separate ingredients with a comma</small>
              </div>
              <div class="modal-form-field">
                {{update_form.cooking_time.label_tag}}
                {{update_form.cooking_time}}
              </div>
              <div class="modal-form-field">
                {{update_form.directions.label_tag}}
                {{update_form.directions}}
              </div>
              <div class="modal-form-field">
                {{update_form.image.label_tag}}
                {{update_form.image}}
              </div>
              <div style="text-align: center;">
                <button type="submit" id="submit-recipe-button">Update Recipe</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Delete recipe modal -->
    <div class="modal fade" id="delete-recipe-modal" tabindex="-1" aria-labelledby="delete-recipe-modal" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="delete-recipe-modal-label">Delete Recipe</h3>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body my-3">
            <h4>Are you sure you want to delete this recipe?</h4>
          </div>
          <div class="modal-footer d-flex justify-content-center">
            <form method="POST" action="{% url 'recipes:delete_recipe' object.id %}">
              {% csrf_token %}
              <button type="submit" class="delete-button">Confirm Delete</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="button-container d-flex justify-content-around">
      <button type="button" class="details-page-button" data-bs-toggle="modal" data-bs-target="#update-recipe-modal">
        Update Recipe
      </button>
      <button type="button" class="details-page-button" data-bs-toggle="modal" data-bs-target="#delete-recipe-modal">
        Delete Recipe
      </button>
      <button class="details-page-button">
        <a href="{% url 'recipes:list' %}" class="back-button-text">Back</a>
      </button>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

src/recipes/templates/recipes/recipes_home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,200;0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <!-- CSS for development, prevents cache loading css file -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}?{% now 'U' %}"> -->
    <title>Recipe App</title>
  </head>

  <body class="home-page">
    <h1 class="home-title">Welcome to the Recipe App!</h1>
    <a href="{% url 'login' %}" class="login-link">Login</a>
    <a href="{% url 'register' %}" class="login-link">Create Account</a>
    <div class="spacer"></div>
    <!-- About modal -->
    <a id="about-modal-link" data-bs-toggle="modal" data-bs-target="#about-modal">
      About
    </a>
    <div class="modal fade" id="about-modal" tabindex="-1" aria-labelledby="aboutModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="modal-title" id="about-modal-label">About the Developer</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body about-modal-body">
            <p>
              The Recipe App is a full-stack web application built with the Django framework that allows
              users to store recipes for future reference or to peruse recipes uploaded by others to find their next great meal!<br>
              This app was developed to grow my understanding of full-stack web application development, specifically with Python and Django, 
              and includes core features of web development such as user authentication, dynamic content creation, and data visualization.<br>
              Thank you for taking the time to check out my Recipe App! If you're interested in my other work, follow the links below.<br>
              <div style="text-align: center;">
                <p>- Kirk Meyer, 2024</p>
              </div>
              <div class="link-container d-flex justify-content-around">
                <a href="https://kirkenstocks.github.io/portfolio-website/" target="_blank" class="about-links">Portfolio</a>
                <a href="https://github.com/Kirkenstocks" target="_blank" class="about-links">GitHub</a>
                <a href="https://www.linkedin.com/in/kirkcmeyer/" target="_blank" class="about-links">LinkedIn</a>
              </div>
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

src/recipes/templates/recipes/recipes_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,200;0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <!-- CSS for development, prevents cache loading file -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}?{% now 'U' %}"> -->
    <title>Recipe App</title>
  </head>
  <body class="recipes-list-page">
    <header class="recipes-list-header">
      <nav class="nav-bar">
        <p class="nav-title">Recipe App</p>
        <a href ="{% url 'logout' %}" class="logout-link">Logout</a>
      </nav>
    </header>
    {% if messages %}
      {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
      {% endfor %}
    {% endif %}
    <div class="button-container d-flex justify-content-around">
      <button id="show-search-button">Search For Recipes</button>
      <button type="button" id="open-add-modal-button" data-bs-toggle="modal" data-bs-target="#add-recipe-modal">
        Add Recipe
      </button>
    </div>
    <!-- Search form -->
    <form action="" method="get" id="recipe-search-form" style="display: none;">
      {% csrf_token %}
      <div class="search-form-field">
        {{search_form.recipe_name.label_tag}}
        {{search_form.recipe_name}}
      </div>
      <div class="search-form-field">
        {{search_form.ingredient.label_tag}}
        {{search_form.ingredient}}
      </div>
      <div class="search-form-field">
        {{search_form.min_cooking_time.label_tag}}
        {{search_form.min_cooking_time}}
      </div>
      <div class="search-form-field">
        {{search_form.max_cooking_time.label_tag}}
        {{search_form.max_cooking_time}}
      </div>
      <div class="search-form-field">
        {{search_form.chart_type.label_tag}}
        {{search_form.chart_type}}
      </div>
      <button type="submit" id="search-button">Search</button>
    </form>
    <!-- Add recipe modal -->
    <div class="modal fade" id="add-recipe-modal" tabindex="-1" aria-labelledby="add-recipe-modal-label" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="add-recipe-modal-label">Add Recipe</h3>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="POST" id="add-recipe-form" action="{% url 'recipes:add_recipe'%}" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="modal-form-field">
                {{add_form.name.label_tag}}
                {{add_form.name}}
              </div>
              <div class="modal-form-field">
                {{add_form.ingredients.label_tag}}
                {{add_form.ingredients}}
                <small>Separate ingredients with a comma</small>
              </div>
              <div class="modal-form-field">
                {{add_form.cooking_time.label_tag}}
                {{add_form.cooking_time}}
              </div>
              <div class="modal-form-field">
                {{add_form.directions.label_tag}}
                {{add_form.directions}}
              </div>
              <div class="modal-form-field">
                {{add_form.image.label_tag}}
                {{add_form.image}}
              </div>
              <div style="text-align: center;">
                <button type="submit" id="submit-recipe-button">Add Recipe</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Recipe cards -->
    <section class="recipe-card-container">
      {% for object in object_list %}
        <div class="recipe-card">
            <img src="{{object.image.url}}" class="recipe-image" alt="Image of {{object.name}}" />
            <h3>
              <a href="{{object.get_absolute_url}}" class="recipe-link">{{object.name}}</a>
            </h3>
        </div>
      {% endfor %}
    </section>
    <hr>
    <!-- Selected chart displayed here -->
    <section class="chart-container">
      <h2 class="analytics-header">Recipe Analytics</h2>
      {% if bar_chart %}
        <img src="data:image/png;base64, {{bar_chart}}" class="chart" alt="Bar chart of most used ingredients">
      {% elif pie_chart %}
        <img src="data:image/png;base64, {{pie_chart}}" class="chart" alt="Pie chart of recipe difficulty distibution">
      {% elif line_chart %}
        <img src="data:image/png;base64, {{line_chart}}" class="chart" alt="Line chart of cooking time for each recipe">
      {% else %}
        <p>Select a chart type above</p>
      {% endif %}
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>